name: Auto-update images.json

on:
  push:
    paths:
      - 'examples/**'

jobs:
  update-images-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          mkdir -p examples
          find examples -maxdepth 1 -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" \) \
          -exec basename {} \; | jq -R . | jq -s . > examples/images.json

      - name: Commit and push updated images.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add examples/images.json
          git commit -m "Auto-update images.json from examples/"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
